import type { Story } from "./story-types";

export const BUNDLED_STORIES: Story[] = [
  {
    id: "diag",
    title: "Diagnostics",
    storyRev: 1,
    rating: "general",
    published: true,
    category: "test",
    allowNameChange: true,
    locale: "en-US",
    config: {
      title: "Diagnostics",
      series: "Diagnostics",
      chapter: 1,
      episode: 1,
      version: 1,
      continuation: false,
      genre: "test",
      category: "test",
      age: "all",
      cover: "night",
      characterCount: 2,
      characters: [
        { id: "jj", name: "J. J.", gender: "male", pronounceAs: "Jay Jay" },
        { id: "beth", name: "Beth", gender: "female", pronounceAs: "Beth" },
      ],
    },
    characters: [
      { id: "jj", defaultName: "J. J.", pronounceAs: "Jay Jay", defaultVoice: "male-low" },
      { id: "beth", defaultName: "Beth", pronounceAs: "Beth", defaultVoice: "female-warm" },
      { id: "narrator", defaultName: "Narrator", defaultVoice: "narrator" },
    ],
    beats: [
      { id: "d1", speaker: "narrator", text: "Diagnostic one. This is the narrator voice only." },
      { id: "d2", speaker: "jj", text: "Diagnostic two. This is the male voice. My name in the story is {{jj}}." },
      {
        id: "d3",
        speaker: "beth",
        text: "Diagnostic three. This is the female voice. My name in the story is {{beth}}.",
      },
      {
        id: "d4",
        speaker: "narrator",
        text: "Diagnostic four. {{jj}} and {{beth}} should have been spoken as the names you typed.",
      },
      { id: "d5", speaker: "jj", text: "Diagnostic five. If you hear this after Beth, cast order is working." },
      { id: "d6", speaker: "beth", text: "Diagnostic six. End of test." },
    ],
  },
  {
    id: "campfire",
    title: "Campfire",
    storyRev: 1,
    rating: "general",
    published: true,
    category: "outdoors",
    allowNameChange: true,
    locale: "en-US",
    config: {
      title: "Campfire",
      series: "Campfire",
      chapter: 1,
      episode: 1,
      version: 1,
      continuation: false,
      genre: "slice-of-life",
      category: "outdoors",
      age: "all",
      cover: "pine",
      characterCount: 2,
      characters: [
        { id: "jj", name: "J. J.", gender: "male", pronounceAs: "Jay Jay" },
        { id: "beth", name: "Beth", gender: "female", pronounceAs: "Beth" },
      ],
    },
    characters: [
      { id: "jj", defaultName: "J. J.", pronounceAs: "Jay Jay", defaultVoice: "male-low" },
      { id: "beth", defaultName: "Beth", pronounceAs: "Beth", defaultVoice: "female-warm" },
      { id: "narrator", defaultName: "Narrator", defaultVoice: "narrator" },
    ],
    beats: [
      {
        id: "b1",
        speaker: "narrator",
        text: "They hiked in late. By the time the fire was going, the pines were black against the sky.",
      },
      {
        id: "b2",
        speaker: "beth",
        text: "No neighbors. No walls. Just the lake, the kettle, and whatever noise the raccoons make.",
      },
      { id: "b3", speaker: "jj", text: "Then we take our time. I packed too much chocolate anyway." },
      {
        id: "b4",
        speaker: "narrator",
        text: "{{beth}} passed {{jj}} the tin mug. The fire popped. The woods went quiet except for them.",
      },
      {
        id: "b5",
        speaker: "beth",
        text: "Tell me the part about getting lost on the ridge. I like that you still pretend it was a shortcut.",
      },
    ],
  },
  {
    id: "campfire-ch2",
    title: "Campfire",
    storyRev: 2,
    rating: "general",
    published: true,
    category: "outdoors",
    allowNameChange: true,
    locale: "en-US",
    config: {
      title: "Campfire",
      series: "Campfire",
      chapter: 2,
      episode: 2,
      version: 2,
      continuation: true,
      genre: "slice-of-life",
      category: "outdoors",
      age: "all",
      cover: "pine",
      characterCount: 2,
      characters: [
        { id: "jj", name: "J. J.", gender: "male", pronounceAs: "Jay Jay" },
        { id: "beth", name: "Beth", gender: "female", pronounceAs: "Beth" },
      ],
    },
    characters: [
      { id: "jj", defaultName: "J. J.", pronounceAs: "Jay Jay", defaultVoice: "male-low" },
      { id: "beth", defaultName: "Beth", pronounceAs: "Beth", defaultVoice: "female-warm" },
      { id: "narrator", defaultName: "Narrator", defaultVoice: "narrator" },
    ],
    beats: [
      { id: "c1", speaker: "narrator", text: "Morning after. The fire was ash. {{beth}} was already packing." },
      {
        id: "c2",
        speaker: "beth",
        text: "Same woods next month, {{jj}}. Don't pretend you forgot the way around that ridge.",
      },
    ],
  },
  {
    id: "nightshift",
    title: "Nightshift",
    storyRev: 1,
    rating: "general",
    published: true,
    category: "workplace",
    allowNameChange: true,
    locale: "en-US",
    config: {
      title: "Nightshift",
      series: "Nightshift",
      chapter: 1,
      episode: 1,
      version: 1,
      continuation: false,
      genre: "workplace",
      category: "workplace",
      age: "all",
      cover: "warehouse",
      characterCount: 2,
      characters: [
        { id: "tony", name: "Tony", gender: "male", pronounceAs: "Toaney" },
        { id: "rae", name: "RaeLynn", gender: "female", pronounceAs: "Rae Lynn" },
      ],
    },
    characters: [
      { id: "tony", defaultName: "Tony", pronounceAs: "Toaney", defaultVoice: "male-low" },
      { id: "rae", defaultName: "RaeLynn", pronounceAs: "Rae Lynn", defaultVoice: "female-warm" },
      { id: "narrator", defaultName: "Narrator", defaultVoice: "narrator" },
    ],
    beats: [
      {
        id: "n1",
        speaker: "narrator",
        text: "The warehouse ran on third shift. Forklifts hummed between racks of Gaylord boxes and bulk bags they all called sacks. Paperwork first. Scan second. Strap and band third. Then the container if the order went out on a box.",
      },
      {
        id: "n2",
        speaker: "narrator",
        text: "{{tony}} had been hired quiet. He checked every pick ticket twice and still asked {{rae}} if the SKU matched. She had been loading longer. She did not mock him for it.",
      },
      {
        id: "n3",
        speaker: "rae",
        text: "Ticket says three Gaylords, two sacks. Barcode on the pallet tag, not the liner. You scan the liner and receiving will bounce it.",
      },
      { id: "n4", speaker: "tony", text: "I scanned the liner last week. I still think about it." },
      {
        id: "n5",
        speaker: "rae",
        text: "I know. That is why I walk the lane with you. Come on. Forks down. Tilt back. We have a container at door four that needs bracing lines before sunrise.",
      },
      {
        id: "n6",
        speaker: "narrator",
        text: "They worked the same two-person cell for months. She taught him how to square a Gaylord on a pallet so the bands would not chew the cardboard. How to find the strap points in a cargo container and run lines so the sacks would not walk in transit. How to sign the pack list like he meant it.",
      },
      {
        id: "n7",
        speaker: "rae",
        text: "Break. Coffee's terrible. Sit anyway. You stopped asking permission to pick the next lane. That took a while.",
      },
      { id: "n8", speaker: "tony", text: "You made it look easy. It isn't. I just stopped pretending I already knew." },
      {
        id: "n9",
        speaker: "narrator",
        text: "They strapped the last Gaylord. They banded the sacks. They ran the lines in the container and signed the paperwork. Nightshift went on. So did they.",
      },
    ],
  },
  {
    id: "river-doesnt-care",
    title: "The River Doesn't Care",
    storyRev: 1, rating: "general", published: true, visibility: "public", category: "outdoors",
    allowNameChange: false, locale: "en-US",
    config: { title: "The River Doesn't Care", series: "Campfire Adventures", chapter: 1, episode: 1, version: 1,
      continuation: false, genre: "adventure-comedy", category: "outdoors", age: "all", cover: "pine", characterCount: 7,
      characters: [
        { id: "jenny", name: "Jenny", gender: "female", pronounceAs: "Jenny" },
        { id: "beth", name: "Beth", gender: "female", pronounceAs: "Beth" },
        { id: "jj", name: "J. J.", gender: "male", pronounceAs: "Jay Jay" },
        { id: "gomer", name: "Gomer", gender: "male", pronounceAs: "Gomer" },
        { id: "reba", name: "Reba", gender: "female", pronounceAs: "Reba" },
        { id: "patsy", name: "Patsy", gender: "female", pronounceAs: "Patsy" },
        { id: "biggie", name: "Biggie", gender: "male", pronounceAs: "Biggie" },
      ] },
    characters: [
      { id: "jenny", defaultName: "Jenny", defaultVoice: "female-warm" },
      { id: "beth", defaultName: "Beth", defaultVoice: "female-warm" },
      { id: "jj", defaultName: "J. J.", pronounceAs: "Jay Jay", defaultVoice: "male-low" },
      { id: "gomer", defaultName: "Gomer", defaultVoice: "male-low" },
      { id: "reba", defaultName: "Reba", defaultVoice: "female-warm" },
      { id: "patsy", defaultName: "Patsy", defaultVoice: "female-warm" },
      { id: "biggie", defaultName: "Biggie", defaultVoice: "male-low" },
      { id: "narrator", defaultName: "Narrator", defaultVoice: "narrator" },
    ],
    beats: [
      { id:"r1",speaker:"narrator",text:"CHAPTER ONE — THE PLAN. By noon Friday the campground road had narrowed to gravel, then dirt, then a two-track beside a broad mountain river." },
      { id:"r2",speaker:"jenny",text:"This is perfect. River, trees, no neighbors close enough to complain, and I brought enough craft supplies to rebuild civilization." },
      { id:"r3",speaker:"beth",text:"You brought three kayaks, rope, beads, wire, paint, a glue gun and something labeled emergency glitter." },
      { id:"r4",speaker:"jenny",text:"Exactly. Prepared." },
      { id:"r5",speaker:"jj",text:"I brought food, water, first aid, repair gear and weather radios. Apparently I misunderstood the assignment." },
      { id:"r6",speaker:"narrator",text:"Gomer stayed close to J. J. The three Chihuahua mixes moved as a unit until Patsy, smallest of them all, surveyed camp like a general arriving at a disputed border." },
      { id:"r7",speaker:"patsy",text:"Perimeter unsecured. Food visible. Humans distracted. Reconnaissance begins now." },
      { id:"r8",speaker:"reba",text:"Beth said stay close." },
      { id:"r9",speaker:"patsy",text:"Beth also thinks we cannot understand English." },
      { id:"r10",speaker:"biggie",text:"Do not speak disrespectfully of Beth." },
      { id:"r11",speaker:"gomer",text:"Small dogs are exhausting." },
      { id:"r12",speaker:"narrator",text:"J. J. scratched Gomer behind the ears." },
      { id:"r13",speaker:"gomer",text:"I would die for this man." },

      { id:"r14",speaker:"narrator",text:"CHAPTER TWO — CAMP RULES. By late afternoon tents were up, hammocks hung and kayaks secured. Jenny and Beth relaxed beside the fire while J. J. studied the next day's paddle route." },
      { id:"r15",speaker:"beth",text:"No work. No schedules. No murder shows until after dark." },
      { id:"r16",speaker:"jenny",text:"And tomorrow we paddle until somebody complains." },
      { id:"r17",speaker:"jj",text:"With this group? Ten minutes." },
      { id:"r18",speaker:"narrator",text:"Gomer settled beside J. J. Reba curled beside Patsy. Biggie pressed himself against Beth." },
      { id:"r19",speaker:"biggie",text:"At last. My beloved understands seating." },
      { id:"r20",speaker:"jj",text:"Biggie, move over." },
      { id:"r21",speaker:"biggie",text:"The husband has spoken. His request has been denied." },
      { id:"r22",speaker:"beth",text:"Why is he staring at you like that?" },
      { id:"r23",speaker:"jj",text:"Apparently I am the other man in my own marriage." },

      { id:"r24",speaker:"narrator",text:"CHAPTER THREE — SOMETHING DOWNSTREAM. Morning arrived bright and warm. Jenny was first on the water, slicing into the current with practiced confidence." },
      { id:"r25",speaker:"jenny",text:"Last one around the bend owes me breakfast." },
      { id:"r26",speaker:"beth",text:"That rule was not discussed." },
      { id:"r27",speaker:"jenny",text:"It was discussed just now." },
      { id:"r28",speaker:"narrator",text:"Two miles downstream Beth spotted an overturned blue kayak lodged against a gravel bar. Above it stood a small orange tent." },
      { id:"r29",speaker:"beth",text:"That is either an abandoned campsite or the opening shot of a murder documentary." },
      { id:"r30",speaker:"jj",text:"There are more than two possibilities in life." },
      { id:"r31",speaker:"beth",text:"Not on television." },
      { id:"r32",speaker:"narrator",text:"They beached. The tent flap stood open. A chair lay on its side. One boot sat near cold ashes. Nobody answered their calls." },
      { id:"r33",speaker:"jenny",text:"Nobody leaves a boat like that if everything is fine." },
      { id:"r34",speaker:"narrator",text:"J. J. found drag marks toward a trail. Jenny found a cracked paddle. Beth found blood on cloth caught in blackberry thorns." },

      { id:"r35",speaker:"narrator",text:"CHAPTER FOUR — THE WEATHER TURNS. The weather radio crackled. A severe storm upstream had stalled over the watershed. Flash flooding was possible by evening." },
      { id:"r36",speaker:"jj",text:"We go back. Now." },
      { id:"r37",speaker:"beth",text:"And whoever owns this camp?" },
      { id:"r38",speaker:"jj",text:"We report the coordinates. If the river rises, three more missing people do not help the first one." },
      { id:"r39",speaker:"jenny",text:"He's right. I hate it, but he's right." },
      { id:"r40",speaker:"narrator",text:"They paddled hard upstream. Rain hammered the river. The easy current turned brown and impatient." },
      { id:"r41",speaker:"narrator",text:"Back at camp the dogs erupted in relief." },
      { id:"r42",speaker:"gomer",text:"J. J. RETURNED. EVERYONE REMAIN CALM. I AM CALM." },
      { id:"r43",speaker:"reba",text:"You are screaming." },
      { id:"r44",speaker:"gomer",text:"CALMLY." },

      { id:"r45",speaker:"narrator",text:"CHAPTER FIVE — PATSY'S CASE. Patsy found a torn strip of orange nylon near the enclosure and followed its scent toward a drainage ditch. Reba, Biggie and Gomer followed." },
      { id:"r46",speaker:"reba",text:"This is how we get in trouble." },
      { id:"r47",speaker:"patsy",text:"History remembers explorers, not dogs who stayed beside the water bowl." },
      { id:"r48",speaker:"biggie",text:"History better have Beth in it." },
      { id:"r49",speaker:"gomer",text:"I miss J. J." },
      { id:"r50",speaker:"narrator",text:"Wedged under a branch was a waterproof orange pack. Patsy barked sharply until Beth came running." },
      { id:"r51",speaker:"patsy",text:"Evidence acquired. Summon the giants." },
      { id:"r52",speaker:"narrator",text:"Inside were a wallet, medication, a cracked satellite messenger and a map with an old riverside shelter circled." },
      { id:"r53",speaker:"beth",text:"Patsy found this?" },
      { id:"r54",speaker:"jj",text:"She has a better evidence-recovery rate than half the shows you watch." },
      { id:"r55",speaker:"beth",text:"Do not insult my shows during an active investigation." },
      { id:"r56",speaker:"patsy",text:"At last, professional recognition." },

      { id:"r57",speaker:"narrator",text:"CHAPTER SIX — THE DECISION. The wallet identified Daniel Mercer. Search crews were delayed by flooded roads." },
      { id:"r58",speaker:"jenny",text:"That shelter is above the flood line. If Daniel got hurt and headed there, he could still be waiting." },
      { id:"r59",speaker:"beth",text:"The blood was limited, but the boot and drag marks suggest a leg injury." },
      { id:"r60",speaker:"jj",text:"We take the ridge trail, first aid, shelter, water and lights. We turn around if conditions become unsafe." },
      { id:"r61",speaker:"jenny",text:"I have paracord." },
      { id:"r62",speaker:"jj",text:"Of course you do." },
      { id:"r63",speaker:"jenny",text:"Three colors." },
      { id:"r64",speaker:"narrator",text:"They left the Chihuahuas secured at camp and took Gomer on leash." },
      { id:"r65",speaker:"patsy",text:"They took the muscle and left command behind." },

      { id:"r66",speaker:"narrator",text:"CHAPTER SEVEN — THE RIDGE. Rain turned the climbing trail slick. Jenny moved lightly. Beth watched for tracks. J. J. checked bearings. Gomer worked with his nose low." },
      { id:"r67",speaker:"gomer",text:"Stranger scent. Blood. Wet leaves. Squirrel. Important squirrel. No. Focus. Stranger." },
      { id:"r68",speaker:"beth",text:"He's pulling toward that ravine." },
      { id:"r69",speaker:"jj",text:"Good boy. Easy, Gomer." },
      { id:"r70",speaker:"gomer",text:"He said good boy. This mission is already a success." },
      { id:"r71",speaker:"narrator",text:"They found Daniel short of the shelter, conscious but shivering. His ankle was badly swollen and a cut on his calf had soaked through a makeshift bandage." },
      { id:"r72",speaker:"beth",text:"Daniel? I'm Beth. We're campers upstream. Help is coming. We're going to get you warm and take care of that leg." },
      { id:"r73",speaker:"narrator",text:"Beth's calm voice steadied him. Jenny turned trekking poles, paracord and a rain fly into support gear while J. J. cleaned and dressed the wound." },
      { id:"r74",speaker:"jenny",text:"Never mock the craft tote." },
      { id:"r75",speaker:"jj",text:"I formally withdraw every statement I have ever made about the craft tote." },

      { id:"r76",speaker:"narrator",text:"CHAPTER EIGHT — HIGH WATER. Moving Daniel to the shelter took nearly an hour. Darkness came early. The river below was no longer murmuring. It was roaring." },
      { id:"r77",speaker:"beth",text:"Tell me we're high enough." },
      { id:"r78",speaker:"jj",text:"For the river, yes. I'm more concerned about the creek behind us." },
      { id:"r79",speaker:"narrator",text:"The creek had become a fast ribbon of muddy water across the return trail. They were staying the night." },
      { id:"r80",speaker:"jenny",text:"Then we make this shelter home until daylight." },
      { id:"r81",speaker:"gomer",text:"Home has J. J. Therefore this is acceptable." },
      { id:"r82",speaker:"narrator",text:"They rationed food, wrapped Daniel in dry layers and waited. Beth kept him talking. Jenny repaired his pack. J. J. checked the radio. Gomer guarded the door." },

      { id:"r83",speaker:"narrator",text:"CHAPTER NINE — BACK AT CAMP. Water crept beneath the dog enclosure. Patsy worried at the tent vestibule zipper until she made an opening." },
      { id:"r84",speaker:"reba",text:"Are we allowed up on the sleeping bag?" },
      { id:"r85",speaker:"patsy",text:"Emergency maritime law." },
      { id:"r86",speaker:"biggie",text:"This smells like Beth." },
      { id:"r87",speaker:"patsy",text:"Please maintain operational discipline." },

      { id:"r88",speaker:"narrator",text:"CHAPTER TEN — RESCUE. The storm passed before dawn. Search-and-rescue radio traffic finally reached J. J.'s handheld. A team could approach from the county road." },
      { id:"r89",speaker:"jj",text:"Rescue team, this is the camping party with Daniel Mercer. Patient conscious, stable, lower-leg injury, sheltered and warm." },
      { id:"r90",speaker:"narrator",text:"Two hours later rescuers arrived. Daniel was transferred onto a litter. Before leaving he thanked Beth, Jenny and J. J. Gomer received a full minute of ear scratches." },
      { id:"r91",speaker:"gomer",text:"Best mission ever." },

      { id:"r92",speaker:"narrator",text:"CHAPTER ELEVEN — THE RETURN. They hiked back exhausted, muddy and hungry. At camp they found three Chihuahuas occupying the center of Beth's sleeping bag." },
      { id:"r93",speaker:"beth",text:"How did you three even get in here?" },
      { id:"r94",speaker:"patsy",text:"Leadership." },
      { id:"r95",speaker:"reba",text:"She chewed the zipper." },
      { id:"r96",speaker:"patsy",text:"Leadership sometimes involves chewing." },
      { id:"r97",speaker:"biggie",text:"Beth! You survived! I never doubted you except constantly." },
      { id:"r98",speaker:"narrator",text:"Biggie launched himself at Beth. Gomer leaned his full weight against J. J.'s legs and sighed." },
      { id:"r99",speaker:"jj",text:"Yeah, buddy. Me too." },

      { id:"r100",speaker:"narrator",text:"CHAPTER TWELVE — THE FIRE. By sunset the campground was drying. The river remained high, so the kayaks stayed ashore. Nobody objected." },
      { id:"r101",speaker:"jenny",text:"I propose we classify this as a successful relaxing weekend." },
      { id:"r102",speaker:"beth",text:"We found an injured stranger, got trapped by floodwater and slept in an abandoned shelter." },
      { id:"r103",speaker:"jenny",text:"Exactly. Nobody checked work email." },
      { id:"r104",speaker:"jj",text:"Hard to argue with that." },
      { id:"r105",speaker:"narrator",text:"Beth and Jenny relaxed beside the fire while J. J. leaned back. The dogs watched every bite of dinner with religious concentration." },
      { id:"r106",speaker:"beth",text:"You know Patsy found the pack that gave us the shelter location." },
      { id:"r107",speaker:"jj",text:"I know. Which means we can never let her know she was right." },
      { id:"r108",speaker:"patsy",text:"Too late." },
      { id:"r109",speaker:"reba",text:"They cannot understand you." },
      { id:"r110",speaker:"patsy",text:"Recognition transcends language." },
      { id:"r111",speaker:"biggie",text:"Beth looked at me. Everyone be quiet." },
      { id:"r112",speaker:"gomer",text:"J. J. has bacon." },

      { id:"r113",speaker:"narrator",text:"CHAPTER THIRTEEN — ONE LAST MYSTERY. At 2:13 in the morning Beth woke to scratching outside the tent." },
      { id:"r114",speaker:"beth",text:"J. J. Something is outside." },
      { id:"r115",speaker:"jj",text:"Raccoon." },
      { id:"r116",speaker:"beth",text:"You do not know that. I watch enough murder shows to know what happens to people who dismiss unexplained noises." },
      { id:"r117",speaker:"biggie",text:"She's right." },
      { id:"r118",speaker:"patsy",text:"Obviously." },
      { id:"r119",speaker:"reba",text:"Could actually be a raccoon." },
      { id:"r120",speaker:"gomer",text:"It is." },
      { id:"r121",speaker:"patsy",text:"How do you know?" },
      { id:"r122",speaker:"gomer",text:"I can smell it." },
      { id:"r123",speaker:"patsy",text:"Show-off." },
      { id:"r124",speaker:"jenny",text:"WHO LEFT THE COOLER UNLATCHED?" },
      { id:"r125",speaker:"narrator",text:"Every dog became perfectly still." },
      { id:"r126",speaker:"patsy",text:"No witnesses." },

      { id:"r127",speaker:"narrator",text:"CHAPTER FOURTEEN — HOME WATER. Sunday brought blue sky. A protected inlet was calm enough for one last easy paddle." },
      { id:"r128",speaker:"jenny",text:"This is what we came for." },
      { id:"r129",speaker:"beth",text:"Technically I came for relaxation." },
      { id:"r130",speaker:"jj",text:"You brought four dogs. That was your first mistake." },
      { id:"r131",speaker:"beth",text:"I brought three dogs. You brought Gomer." },
      { id:"r132",speaker:"gomer",text:"Correct. I belong to J. J." },
      { id:"r133",speaker:"beth",text:"See? Even his face agrees with me." },
      { id:"r134",speaker:"narrator",text:"They drifted beneath a clean morning sky. Jenny rested her paddle. Beth watched a heron lift from the bank. J. J. let his kayak turn slowly with the current." },

      { id:"r135",speaker:"narrator",text:"CHAPTER FIFTEEN — NEXT TIME. Packing took most of the afternoon. Jenny braided scraps of orange rescue cord into tiny keepsakes for the dogs." },
      { id:"r136",speaker:"jenny",text:"Medals for distinguished service." },
      { id:"r137",speaker:"patsy",text:"At last." },
      { id:"r138",speaker:"reba",text:"Mine is pretty." },
      { id:"r139",speaker:"biggie",text:"Does Beth like mine?" },
      { id:"r140",speaker:"gomer",text:"Can I eat mine?" },
      { id:"r141",speaker:"beth",text:"Same place next year?" },
      { id:"r142",speaker:"jj",text:"After I check the flood history." },
      { id:"r143",speaker:"jenny",text:"I'll bring more paracord." },
      { id:"r144",speaker:"patsy",text:"I will prepare a revised operational plan." },
      { id:"r145",speaker:"reba",text:"Can the revised plan include naps?" },
      { id:"r146",speaker:"biggie",text:"And Beth?" },
      { id:"r147",speaker:"gomer",text:"And bacon?" },
      { id:"r148",speaker:"patsy",text:"Fine. Naps, Beth and bacon. Meeting adjourned." },
      { id:"r149",speaker:"narrator",text:"The vehicles climbed the gravel road toward home. Behind them the river kept moving through the mountains, carrying rainwater and secrets downstream. Wild water made no promises. Respect it, prepare for it, and never mistake a peaceful morning for certainty. But the people in the cars were laughing, the dogs were asleep, and plans for the next trip had already begun." },
    ],
  },
];
