import type { Story } from "./story-types";

export const BUNDLED_STORIES: Story[] = [
  {
    id: "diag",
    title: "Diagnostics",
    storyRev: 1,
    rating: "general",
    published: true,
    category: "test",
    allowNameChange: true,
    locale: "en-US",
    config: {
      title: "Diagnostics",
      series: "Diagnostics",
      chapter: 1,
      episode: 1,
      version: 1,
      continuation: false,
      genre: "test",
      category: "test",
      age: "all",
      cover: "night",
      characterCount: 2,
      characters: [
        { id: "jj", name: "J. J.", gender: "male", pronounceAs: "Jay Jay" },
        { id: "beth", name: "Beth", gender: "female", pronounceAs: "Beth" },
      ],
    },
    characters: [
      { id: "jj", defaultName: "J. J.", pronounceAs: "Jay Jay", defaultVoice: "male-low" },
      { id: "beth", defaultName: "Beth", pronounceAs: "Beth", defaultVoice: "female-warm" },
      { id: "narrator", defaultName: "Narrator", defaultVoice: "narrator" },
    ],
    beats: [
      { id: "d1", speaker: "narrator", text: "Diagnostic one. This is the narrator voice only." },
      { id: "d2", speaker: "jj", text: "Diagnostic two. This is the male voice. My name in the story is {{jj}}." },
      {
        id: "d3",
        speaker: "beth",
        text: "Diagnostic three. This is the female voice. My name in the story is {{beth}}.",
      },
      {
        id: "d4",
        speaker: "narrator",
        text: "Diagnostic four. {{jj}} and {{beth}} should have been spoken as the names you typed.",
      },
      { id: "d5", speaker: "jj", text: "Diagnostic five. If you hear this after Beth, cast order is working." },
      { id: "d6", speaker: "beth", text: "Diagnostic six. End of test." },
    ],
  },
  {
    id: "campfire",
    title: "Campfire",
    storyRev: 1,
    rating: "general",
    published: true,
    category: "outdoors",
    allowNameChange: true,
    locale: "en-US",
    config: {
      title: "Campfire",
      series: "Campfire",
      chapter: 1,
      episode: 1,
      version: 1,
      continuation: false,
      genre: "slice-of-life",
      category: "outdoors",
      age: "all",
      cover: "pine",
      characterCount: 2,
      characters: [
        { id: "jj", name: "J. J.", gender: "male", pronounceAs: "Jay Jay" },
        { id: "beth", name: "Beth", gender: "female", pronounceAs: "Beth" },
      ],
    },
    characters: [
      { id: "jj", defaultName: "J. J.", pronounceAs: "Jay Jay", defaultVoice: "male-low" },
      { id: "beth", defaultName: "Beth", pronounceAs: "Beth", defaultVoice: "female-warm" },
      { id: "narrator", defaultName: "Narrator", defaultVoice: "narrator" },
    ],
    beats: [
      {
        id: "b1",
        speaker: "narrator",
        text: "They hiked in late. By the time the fire was going, the pines were black against the sky.",
      },
      {
        id: "b2",
        speaker: "beth",
        text: "No neighbors. No walls. Just the lake, the kettle, and whatever noise the raccoons make.",
      },
      { id: "b3", speaker: "jj", text: "Then we take our time. I packed too much chocolate anyway." },
      {
        id: "b4",
        speaker: "narrator",
        text: "{{beth}} passed {{jj}} the tin mug. The fire popped. The woods went quiet except for them.",
      },
      {
        id: "b5",
        speaker: "beth",
        text: "Tell me the part about getting lost on the ridge. I like that you still pretend it was a shortcut.",
      },
    ],
  },
  {
    id: "campfire-ch2",
    title: "Campfire",
    storyRev: 2,
    rating: "general",
    published: true,
    category: "outdoors",
    allowNameChange: true,
    locale: "en-US",
    config: {
      title: "Campfire",
      series: "Campfire",
      chapter: 2,
      episode: 2,
      version: 2,
      continuation: true,
      genre: "slice-of-life",
      category: "outdoors",
      age: "all",
      cover: "pine",
      characterCount: 2,
      characters: [
        { id: "jj", name: "J. J.", gender: "male", pronounceAs: "Jay Jay" },
        { id: "beth", name: "Beth", gender: "female", pronounceAs: "Beth" },
      ],
    },
    characters: [
      { id: "jj", defaultName: "J. J.", pronounceAs: "Jay Jay", defaultVoice: "male-low" },
      { id: "beth", defaultName: "Beth", pronounceAs: "Beth", defaultVoice: "female-warm" },
      { id: "narrator", defaultName: "Narrator", defaultVoice: "narrator" },
    ],
    beats: [
      { id: "c1", speaker: "narrator", text: "Morning after. The fire was ash. {{beth}} was already packing." },
      {
        id: "c2",
        speaker: "beth",
        text: "Same woods next month, {{jj}}. Don't pretend you forgot the way around that ridge.",
      },
    ],
  },
  {
    id: "nightshift",
    title: "Nightshift",
    storyRev: 1,
    rating: "general",
    published: true,
    category: "workplace",
    allowNameChange: true,
    locale: "en-US",
    config: {
      title: "Nightshift",
      series: "Nightshift",
      chapter: 1,
      episode: 1,
      version: 1,
      continuation: false,
      genre: "workplace",
      category: "workplace",
      age: "all",
      cover: "warehouse",
      characterCount: 2,
      characters: [
        { id: "tony", name: "Tony", gender: "male", pronounceAs: "Toaney" },
        { id: "rae", name: "RaeLynn", gender: "female", pronounceAs: "Rae Lynn" },
      ],
    },
    characters: [
      { id: "tony", defaultName: "Tony", pronounceAs: "Toaney", defaultVoice: "male-low" },
      { id: "rae", defaultName: "RaeLynn", pronounceAs: "Rae Lynn", defaultVoice: "female-warm" },
      { id: "narrator", defaultName: "Narrator", defaultVoice: "narrator" },
    ],
    beats: [
      {
        id: "n1",
        speaker: "narrator",
        text: "The warehouse ran on third shift. Forklifts hummed between racks of Gaylord boxes and bulk bags they all called sacks. Paperwork first. Scan second. Strap and band third. Then the container if the order went out on a box.",
      },
      {
        id: "n2",
        speaker: "narrator",
        text: "{{tony}} had been hired quiet. He checked every pick ticket twice and still asked {{rae}} if the SKU matched. She had been loading longer. She did not mock him for it.",
      },
      {
        id: "n3",
        speaker: "rae",
        text: "Ticket says three Gaylords, two sacks. Barcode on the pallet tag, not the liner. You scan the liner and receiving will bounce it.",
      },
      { id: "n4", speaker: "tony", text: "I scanned the liner last week. I still think about it." },
      {
        id: "n5",
        speaker: "rae",
        text: "I know. That is why I walk the lane with you. Come on. Forks down. Tilt back. We have a container at door four that needs bracing lines before sunrise.",
      },
      {
        id: "n6",
        speaker: "narrator",
        text: "They worked the same two-person cell for months. She taught him how to square a Gaylord on a pallet so the bands would not chew the cardboard. How to find the strap points in a cargo container and run lines so the sacks would not walk in transit. How to sign the pack list like he meant it.",
      },
      {
        id: "n7",
        speaker: "rae",
        text: "Break. Coffee's terrible. Sit anyway. You stopped asking permission to pick the next lane. That took a while.",
      },
      { id: "n8", speaker: "tony", text: "You made it look easy. It isn't. I just stopped pretending I already knew." },
      {
        id: "n9",
        speaker: "narrator",
        text: "They strapped the last Gaylord. They banded the sacks. They ran the lines in the container and signed the paperwork. Nightshift went on. So did they.",
      },
    ],
  },
];
