/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CastSlugRouteImport } from './routes/cast.$slug'
import { Route as ListenStoryIdRouteImport } from './routes/listen.$storyId'
import { Route as SeriesSlugRouteImport } from './routes/series.$slug'
import { Route as ShareTokenRouteImport } from './routes/share.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CastSlugRoute = CastSlugRouteImport.update({
  id: '/cast/$slug',
  path: '/cast/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenStoryIdRoute = ListenStoryIdRouteImport.update({
  id: '/listen/$storyId',
  path: '/listen/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugRoute = SeriesSlugRouteImport.update({
  id: '/series/$slug',
  path: '/series/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cast/$slug': typeof CastSlugRoute
  '/listen/$storyId': typeof ListenStoryIdRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/share/$token': typeof ShareTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cast/$slug': typeof CastSlugRoute
  '/listen/$storyId': typeof ListenStoryIdRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/share/$token': typeof ShareTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cast/$slug': typeof CastSlugRoute
  '/listen/$storyId': typeof ListenStoryIdRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/share/$token': typeof ShareTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cast/$slug'
    | '/listen/$storyId'
    | '/series/$slug'
    | '/share/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cast/$slug'
    | '/listen/$storyId'
    | '/series/$slug'
    | '/share/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cast/$slug'
    | '/listen/$storyId'
    | '/series/$slug'
    | '/share/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CastSlugRoute: typeof CastSlugRoute
  ListenStoryIdRoute: typeof ListenStoryIdRoute
  SeriesSlugRoute: typeof SeriesSlugRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cast/$slug': {
      id: '/cast/$slug'
      path: '/cast/$slug'
      fullPath: '/cast/$slug'
      preLoaderRoute: typeof CastSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen/$storyId': {
      id: '/listen/$storyId'
      path: '/listen/$storyId'
      fullPath: '/listen/$storyId'
      preLoaderRoute: typeof ListenStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug': {
      id: '/series/$slug'
      path: '/series/$slug'
      fullPath: '/series/$slug'
      preLoaderRoute: typeof SeriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CastSlugRoute: CastSlugRoute,
  ListenStoryIdRoute: ListenStoryIdRoute,
  SeriesSlugRoute: SeriesSlugRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
